### ISSUE TITLE
Weird glitch in the index of the Bibliography

### ISSUE THREAD

**Issue by jcommelin** [stacks/stacks-website#100]
In the sidebar of
http://stacks.math.columbia.edu/bibliography
the index appears totally messed up.

![2015-03-04-103007_313x146_scrot](https://cloud.githubusercontent.com/assets/5636705/6480888/cb5b6ffe-c258-11e4-8039-7327c5ec269f.png)

**Comment by pbelmans** [comment]
For my future self: it fails in Firefox. It is probably due `list-style-type: none;` not triggering correctly.

**Comment by aisejohan** [comment]
My firefox 31.4.0 renders it correctly

**Comment by pbelmans** [comment]
It fails in some version of Firefox 33 and 37. A fix will be pushed later today, my earlier guess was correct: apparently `div#sidebar ol` in `css/main.css` takes preference over `ol#index` in `css/bibliography.css`, I guess I should read up on these rules and see whether my interpretation or Firefox's implementation is wrong.
