### ISSUE TITLE
Visualisation: position of results in the Stacks project

### ISSUE THREAD

**Issue by pbelmans** [stacks/stacks-website#103]
Maybe the following is an interesting visualisation to beef up the statistics page a little: we plot all available tags, from 0000 to 0B50 (at the moment) from left to right on the x-axis, with the relative position in the Stacks project on the y-axis. This might show where stretches of the growth of the Stacks project have occurred, and to which extent developments in later chapters induce new tags in earlier chapters. Just an idea.

**Comment by jcommelin** [comment]
Sounds like fun. If I understand you it has mostly a historical value,
right?

**Comment by pbelmans** [comment]
No clue what historical value means.

It'd be a visualisation of _how the Stacks project grows_, i.e. not only at the very end. One minor remark: there is both the current relative position, and the original relative position. Both might be interesting.

**Comment by jcommelin** [comment]
Ok, what I meant is that it does not really have a mathematical value, but
visualises history. In hindsight I was just repeating what you said.

In reply to your other paragraph: I think it is not so easy to visualise
both relative positions (current and original) in one graphic. Do you have
an idea for this, or do you want two different graphics?

**Comment by pbelmans** [comment]
Two different graphics then. The most important issue is the insane resolution on the x-axis (14k data points and growing...), which'll require some scrolling.

**Comment by jcommelin** [comment]
Yes, a lot of scrolling. But the resolution on the y-axis is just as large,
right? (You want to plot the graph of a permutation, or not?) Maybe we want
some sort of autoscrolling for the y-axis (and a minimap like in Sublime
Text!!!).

**Comment by pbelmans** [comment]
The vertical resolution is less important: it should be correct, but not necessarily distinguishable, i.e. rescaling wouldn't destroy the interpretation of the data. The horizontal axis must have all points though, although some clustering algorithm could be applied here if one were to implement zooming.

**Comment by pbelmans** [comment]
By the way, it is not a permutation. The y-axis are the pages.

**Comment by jcommelin** [comment]
Aah, that makes sense! And then the resolution decreases a lot. Good point.

**Comment by pbelmans** [comment]
This is now addressed in stacks/stacks-scatter.
