### ISSUE TITLE
Text in math render issue

### ISSUE THREAD

**Issue by pbelmans** [stacks/stacks-website#129]
See http://stacks.math.columbia.edu/tag/0AKX#comment-1911

**Comment by aisejohan** [comment]
Not an important problem as this almost never comes up. Really, the issue is with the Stacks project itself where we might need to do a better job with text in statements of lemmas, etc, as Brian Conrad suggested in one of his recent comments.

**Comment by pbelmans** [comment]
Not a bug, see [this comment](http://stacks.math.columbia.edu/tag/0AKX#comment-2104).
