### ISSUE TITLE
List commits changing tag

### ISSUE THREAD

**Issue by aisejohan** [stacks/stacks-website#91]
Find the commits which change a given tag and display the commit messages.

Rationale: I worry about the "changing history" aspect of the Stacks project and I want it to be easier for visitors to see how the material got changed over time, why it got changed, and who contributed. This is documented in the commit log (I try to write commit messages that actually explain what is going on) of the Stacks project but nowhere else. I want it to be very clear to visitors we are never hiding, or revising history, or anything like that.

Example: Recently I got a message of Ofer Gabber explaining a gap in the proof of <a href="http://stacks.math.columbia.edu/tag/053F">Lemma Tag 053F</a>. This made it necessary to move the lemma, and actually, made the lemma effectively obsolete. Currently, the statistics page does have a link to the commit moving the lemma, because this changed the latex label. But, if I had first changed the lemma in one commit and then moved it in a second commit, only the second one would have shown up.

To implement this there are two parts:

  1. Think carefully about what it means to trace the history of a tag through the stacks project and write a script that does the job and adds this information to the database. I will make an issue for stacks-tools about this.

  2. Adapt the statistics page to show this information. I'd like to replace what we have now with a list of commits and a mechanism to show the commit message as well as a link to the github page of the commit.

**Comment by pbelmans** [comment]
I'm not sure what you want here. The statistics page for this tag already links [the relevant commit](https://github.com/stacks/stacks-project/commit/42875075c582d41c156940ffc5c384deef2b9214) I think. Or is this not the relevant commit?

**Comment by aisejohan** [comment]
This is now done as we have the history pages on the website . See 7470b8328ac08d535d862999f3adbd14391ba580
