### ISSUE TITLE
Recent comments pages are borked

### ISSUE THREAD

**Issue by aisejohan** [stacks/stacks-website#97]
There is something wrong with the later recent comments pages. They say there are 20 comments shown, but in reality it shows many more. This is confusing if you've scrolled down the page and then go to the next page for the next set of comments, because there is overlap.

Moreover, currently the first page shows comments 1253 -- 1234 and the second page shows comments 1229 -- 1186 so in this case there is a gap rather than an overlap (sorry no there is no gap because I deleted comments 1230, 1231, 1232, 1233 because there was weird stuff in there that upset my feed reader). The third page shows 1208 -- 1145 (so about 63!).

**Comment by pbelmans** [comment]
What a silly bug... It's already fixed on the server.
